// <auto-generated />
using HeatExchangeApp.Models.Additional_Classes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeatExchangeApp.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HeatExchangeApp.Models.InitData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgGasHeatCapacity")
                        .HasColumnType("REAL");

                    b.Property<double>("GasSpeed")
                        .HasColumnType("REAL");

                    b.Property<int?>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<double>("InitTempGas")
                        .HasColumnType("REAL");

                    b.Property<double>("InitTempMaterial")
                        .HasColumnType("REAL");

                    b.Property<double>("LayerHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("MachineDiameter")
                        .HasColumnType("REAL");

                    b.Property<double>("MaterialHeatCapacity")
                        .HasColumnType("REAL");

                    b.Property<double>("MaterialRate")
                        .HasColumnType("REAL");

                    b.Property<double>("VolCoeffHeatTransfer")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("InitData");
                });

            modelBuilder.Entity("HeatExchangeApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
